# Generated by Django 3.2.5 on 2021-07-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_modules_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='country',
            field=models.TextField(default='CL', max_length=3, verbose_name='Country'),
        ),
    ]
