# Generated by Django 3.2.11 on 2022-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20210711_2234"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Module",
        ),
        migrations.RemoveField(
            model_name="coreuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="coreuser",
            name="tz",
        ),
        migrations.AddField(
            model_name="coreuser",
            name="phone",
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="coreuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name="Phone",
        ),
    ]
