# Generated by Django 4.1 on 2022-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20220109_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreuser",
            name="phone",
            field=models.CharField(
                default=None, max_length=150, null=True, unique=True
            ),
        ),
    ]
