# Generated by Django 4.1.3 on 2022-11-12 06:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_coreuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Correo"),
                            ("sms", "SMS"),
                            ("voice", "Voice"),
                            ("whatsapp", "Whatsapp"),
                            ("telegram", "Telegram"),
                            ("email_sync", "Email (Sync)"),
                            ("webpush", "Browser Push"),
                            ("url", "HTTP/S"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_sent", "Not Sent"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_sent",
                        max_length=10,
                    ),
                ),
                ("to", models.CharField(max_length=2048)),
                ("orig", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=180)),
                ("text", models.TextField(blank=True, default=None, null=True)),
                ("html", models.TextField(blank=True, default=None, null=True)),
                (
                    "headers",
                    jsonfield.fields.JSONField(blank=True, default=None, null=True),
                ),
                ("result", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name_plural": "Messages",
            },
        ),
    ]
